// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        /*throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );*/
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4QolnAhgYqIrRqUPigj2VfPO578pPp1k',
    appId: '1:550128233714:web:b64197c22491dce4c5746b',
    messagingSenderId: '550128233714',
    projectId: 'dartotsu-app',
    authDomain: 'dartotsu-app.firebaseapp.com',
    storageBucket: 'dartotsu-app.firebasestorage.app',
    measurementId: 'G-75TFL5TSHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI721f78Tm4n-4fejwE8hiKVQtqzRAZUs',
    appId: '1:550128233714:android:2318b57544f3c78ac5746b',
    messagingSenderId: '550128233714',
    projectId: 'dartotsu-app',
    storageBucket: 'dartotsu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5uy9PR2s0CUmesztQg1fEEo_TMMqbqco',
    appId: '1:550128233714:ios:2bd81777a2005d7cc5746b',
    messagingSenderId: '550128233714',
    projectId: 'dartotsu-app',
    storageBucket: 'dartotsu-app.firebasestorage.app',
    iosBundleId: 'ani.aayush262.dartotsu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5uy9PR2s0CUmesztQg1fEEo_TMMqbqco',
    appId: '1:550128233714:ios:2bd81777a2005d7cc5746b',
    messagingSenderId: '550128233714',
    projectId: 'dartotsu-app',
    storageBucket: 'dartotsu-app.firebasestorage.app',
    iosBundleId: 'ani.aayush262.dartotsu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4QolnAhgYqIrRqUPigj2VfPO578pPp1k',
    appId: '1:550128233714:web:b64197c22491dce4c5746b',
    messagingSenderId: '550128233714',
    projectId: 'dartotsu-app',
    authDomain: 'dartotsu-app.firebaseapp.com',
    storageBucket: 'dartotsu-app.firebasestorage.app',
    measurementId: 'G-75TFL5TSHL',
  );
}
