name: build
on:
  push:
    branches: main

jobs:
  build_android:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'duck')
    permissions:
      contents: write     
      pull-requests: read
      actions: read

    steps:
      - name: Cloning repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download last SHA artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: justanother.yml
          name: last-sha
        continue-on-error: true
      - name: Save Current SHA for Next Run
        run: |
            echo ${{ github.sha }} > last_sha.txt
            LAST_SHA=$(cat last_sha.txt)
            echo "prevSha=$LASt_SHA" >> $GITHUB_ENV
    

      - name: Delete tag 
        uses: actions/github-script@v6 
        with: 
          script: | 
            const octokit = github.getOctokit(${{secrets.GITHUB_TOKEN}}); 
            await octokit.git.deleteRef({ 
                owner: context.repo.owner, 
                repo: context.repo.repo, 
                ref: 'refs/tags/build-${{ env.prevSha }}' 
            });
        continue-on-error: true
      - name: Create GitHub Prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "build-${{ github.sha }}"
          release_name: "Build for Commit ${{ github.sha }}"
          draft: false            # Set to false to publish the release (not a draft)
          prerelease: true       # Set to true to mark it as a prerelease

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./scripts/testFile.txt
          asset_name: testFile.txt
          asset_content_type: Text/plain

      - name: Post to Discord
        run: |
          # Constructing the correct URL for the prerelease
          release_url="https://github.com/${{ github.repository }}/releases/tag/build-${{ github.sha }}"
          echo "Release URL: $release_url"  # Debugging output to check URL format
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"A new Android APK has been built and is available as a prerelease: ${release_url}. Please test and review.\"}" \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"

      - name: Upload Current SHA as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: last-sha
          path: last_sha.txt

